### ISSUE TITLE
Make compatible with AnkiMobile & Anki-Android

### ISSUE THREAD

**Issue by phu54321** [trgkanki/remaining_time#1]
Since this program only needs SVG and HTML support to work correctly, I think that the addon may be injected directly into card formats. When the addon is installed, the addon will inject its code to every exiting model's HTML & CSS.

Problem
- Detect when the 'current deck' has changed, or at least when the review is interrupted. I doubt if AnkiMobile or Anki-Android exposes those things to JS area.
- Detect the current progress, as this is, frankly, essential for accurate estimation.
- Check if `window.localStorage` is supported in both platforms, as I think that could be persistent between review sessions.

**Comment by phu54321** [comment]
Compativility w/ ankidroid - possible resource

https://www.reddit.com/r/Anki/comments/gtcysk/how_should_implement_progress_bar_in_ankidroid/?utm_medium=android_app&utm_source=share

**Comment by phu54321** [comment]
Awesomely this has been fixed. Really. :)

**Comment by TowelSniffer** [comment]
I can see this issue has been closed but I wanted to ask if this in fact works for other people. I tried enabling the config setting but when I edit a card I get this error message 
```
Debug info:
Anki 2.1.34 (8af8f565) Python 3.8.0 Qt 5.15.1 PyQt 5.15.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-23 21:33:47

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 541, in _onBridgeCmd
  File "aqt\gui_hooks.py", line 2959, in __call__
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\1508357010\utils\JSCallable.py", line 29, in _onBridgeMessage
    ret = func(*argList)
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\1508357010\jsapi\remainingCardCount.py", line 14, in getCurrentRemainingCardCount
    counts = list(mw.col.sched.counts(reviewer.card))
  File "anki\schedv2.py", line 162, in counts
AttributeError: 'Scheduler' object has no attribute 'newCount'
```
I can see that it tries to load `<!-- # 2eecab49dc1f9618 --><script src="_remainingtime.min.js"></script><!-- / 2eecab49dc1f9618 -->` within the note templates but it wont work on ankidroid for me.

**Comment by phu54321** [comment]
Wtf. this seems like a bug in Anki.

**Comment by phu54321** [comment]
Addon not working on ankidroid. Bug reproduced
