### ISSUE TITLE
Cards per minute feature request.

### ISSUE THREAD

**Issue by Mike7154** [trgkanki/remaining_time#10]
# Feature request

## Problem description

This addon is great, and every time you update it I manually add this feature myself, but with the most recent update, everything moved around and I can't easily find the python file to modify. Essentially, it shows how fast I am going through cards by showing a cards/minute. I am sure I could figure it out and keep doing what I've been doing, maybe when I have time. This one change made my cards/minute speed increase substantially because I can have a speed goal and know if I'm going slow. ETA kind of serves this purpose to keep me motivated and going fast, but I still can't tell if I'm going slow without the cards/minute statistic. I think it would be more valuable than ETA, because ETA is almost the same as remaining time.

## Suggested solution

Here is the code I added for the previous version (before the update)
message = "Elapsed %s, Remaining %s, Total %s, CPM %s" % (
   t2s(elapsedTime),
   t2s(remainingTime),
   t2s(elapsedTime + remainingTime),
   round(estimator.getSlope()*60,2)
)

## Alternative solutions you've thought of\

> A clear and concise description of any alternative solutions or features you've considered.
 - If this is added, maybe make it an option. "Add cards/minute" yes/no. Because I know some people won't like all these extra statistics crowding the bar.

## Additional context

> Add any other context or screenshots about the feature request here.

**Comment by phu54321** [comment]
Seems like a good idea. I'm trying to do updates every Sunday (KST, GMT+9), so stay tuned :)

The current codebase is based on typescript and minified upon distribution, so it's rather hard for end-users to update the code.
If there are other features you've added yourself and want to integrate, feel free to issue PR.

**Comment by phu54321** [comment]
Related to #4. Since https://github.com/trgkanki/addon_template/commit/4863070e373dcc0fb7fec2928d6d52d52d04fd8f, this is now feasible.

ETA this sunday

**Comment by phu54321** [comment]
Now you can customize addon config to add CPM on bar message!

**Comment by Mike7154** [comment]
> Now you can customize addon config to add CPM on bar message!

WOW, WOW, WOW. This addon just became perfect!! Thanks a ton
