### ISSUE TITLE
I think your addon throws an error that stops the webview inspector

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [trgkanki/remaining_time#14]
# Bug report

## Describe the bug

As you can see in [this error](https://github.com/hikaru-y/anki21-addon-ankiwebview-inspector/issues/2) report I filed initially in webview debugger, when reviewing and clicking on "inspect" using the right mouse click I instantly get the following yellow error in the console : `DevTools failed to parse SourceMap: http://127.0.0.1:40511/main.min.js.map`

I think this error stops the js from correctly working and stops me from accessing js objects.

## Reproduction step

> Steps to reproduce the behavior:

1. Start reviewing a card
2. Right click, "inspect"
3. See error

## Expected behavior

No error and unhindered javascript

## Actual behavior

An yellow error appears and js seems unusable, I can't use document.getElementsById for example.

## Anki/OS versions

- OS: Ubuntu 18.04
- Anki version 2.1.33

## Additional context

I was able to workaround this by removing the line of the template that is loading the code : `<!-- # 2eecab49dc1f9618 --><script src="_remainingtime.min.js"></script><!-- / 2eecab49dc1f9618 -->` and disabling the addon.

**Comment by phu54321** [comment]
Ok so this bug occured on anki 2.1.33?

**Comment by thiswillbeyourgithub** [comment]
I was previously on 2.1.15 I think, so somewhere in between. Sorry

**Comment by phu54321** [comment]
Fixed by disabling sourcemap
