### ISSUE TITLE
Bar displays at the top of the screen in AnkiDroid instead of the bottom

### ISSUE THREAD

**Issue by talenelat-elin** [trgkanki/remaining_time#17]
# Bug report

## Describe the bug

> The progress bar does not go to the bottom of the screen in ankidroid, despite it being configured to do so. It does go to bottom in Windows but does not do so in AnkiDroid which is linked to the same profile.

## Reproduction step

>In the config file for this addon in the Addon Menu in Anki for Windows: set the  `"showAtBottom"` property to `true` 
Sync the profile in Windows
Sync the profile in AnkiDroid
Open reviewer in AnkiDroid

## Expected behavior
> It should have displayed at the bottom of the screen in AnkiDroid and Windows

## Actual behavior

>On the PC:
![image](https://user-images.githubusercontent.com/71895835/94865506-5a647480-045b-11eb-868f-3043a12e6461.png)
In AnkiDroid:
![image](https://user-images.githubusercontent.com/71895835/94865127-b4b10580-045a-11eb-8f71-af7e20a871b8.png).

## Anki/OS versions
Anki For windows 2.1.33
AnkiDroid 2.13.3
Addon Fully Updated
## Additional context
> I have tried check media, and syncing media.
I have tried deleting the addon, then deleting the remainingtime.js script and config js files from the media folder from both devices, and reinstalling the addon on the pc and immediately without restarting anki, changing the settings to show at bottom, and only then restarting anki on pc, and then syncing to AnkiDroid to see if the problem persists, and it does.

**Comment by phu54321** [comment]
bump
