### ISSUE TITLE
Ignore Times Longer than x when computing CPM and remaining time

### ISSUE THREAD

**Issue by MikeDacre** [trgkanki/remaining_time#19]
# Feature request: Ignore Times Longer than x when computing CPM and remaining time

## Problem description

I frequently step away from anki in the middle of mammoth multi-hour review sessions, and when I come back my remaining time is totally messed up and never really corrects.

## Suggested solution

It would be great to have a config item to enable ignoring times greater than x seconds (e.g. 60) in computing CPM and remaining time. It makes sense for this to be optional as perhaps this issue doesn't affect most people.

Possibly you could use the max time set by the deck instead, but I feel like this may be somewhat more cumbersome to implement.

**Comment by phu54321** [comment]
Not really in config, but we limit review time to 5 minute. Any review taking more than that is thought to be 5 minutes.

1 minute is too short. This addon estimates time, so if one frequently stops 2 minute between each reviews that should be accounted. (Btw its me)

**Comment by phu54321** [comment]
Merging issue to #24
