### ISSUE TITLE
Unable to use Hint Hotkeys Addon with Remaining Time plugin

### ISSUE THREAD

**Issue by AnkiCollabUTMC** [trgkanki/remaining_time#2]
Hint hotkeys is an addon used with with the anking medical school anki deck
[https://ankiweb.net/shared/info/1844908621]

H reveals one hint and G reveals all hints. 

Unfortunately the hotkey to reset progress/remaining time is also H on your addon.

Could you add a way to change the hotkey for resetting the remaining time?

**Comment by hkhiem** [comment]
Hi. I'm having the exact same problem but I can't find RemainingTime.py to modify it.

I can't even find 
barEl.html("{message} &nbsp; <a href=# onclick=\\"pycmd('_rt_pgreset');return false;\\" title='Reset progress bar for this deck'>[⥻]</a>")

Only thing I was able to find with "onclick" was in the Button.py. 

Would appreciate your help. I don't know anything about coding so this is very foreign to me already.

**Comment by phu54321** [comment]
Due to transition to typescript, the fix seems to have disappeared. Fix will be issued today. 👍
