### ISSUE TITLE
Weird Error When Logging In To Anki

### ISSUE THREAD

**Issue by nfateema** [trgkanki/remaining_time#21]
Hi, I'm attaching an image of the error I keep getting when signing in to Anki. I absolutely love your addon so I'm sad to see it not working. Please let me know what to do! I'm heading over to your patreon page to become a patron if that helps!

![80495419-150C-4772-962D-B37FAE7C0904_1_105_c](https://user-images.githubusercontent.com/73708597/97724454-500db880-1aa3-11eb-8f26-7b92ce0e80f9.jpeg)

**Comment by phu54321** [comment]
Update Anki to the latest version. At least 2.1.26.
