### ISSUE TITLE
Where can I change colors?

### ISSUE THREAD

**Issue by spectre008** [trgkanki/remaining_time#22]
Hi, I think I have a problem with colors. Where can I change them?

**Comment by spectre008** [comment]
![Screen Shot 2020-10-31 at 10 47 01 AM](https://user-images.githubusercontent.com/61936843/97774172-bf98ac00-1b66-11eb-8b12-0756068a9db3.png)
I pressed "Again" and "Good". And I don't see Rate.

**Comment by phu54321** [comment]
Please fill in the bug template format.

**Comment by spectre008** [comment]
I see. Could you tell where I can change the colors?
