### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ghost** [trgkanki/remaining_time#23]
![image](https://user-images.githubusercontent.com/61936843/97776817-74899380-1b7c-11eb-9865-abc98a562cdf.png)
I pressed "Again" and "Good" and my colors are the same. As well I don't see Rate. Where can I change the colors?

**Comment by phu54321** [comment]
1. There's a bug template that looks like this. Please modify your question to match this template.

```
# Bug report

## Describe the bug

> A clear and concise description of what the bug is.

## Reproduction step

> Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior

> A clear and concise description of what you expected to happen.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

## Anki/OS versions

- OS: *[ex: macOS Catalina, Windows 10, Ubuntu 18.04]*
- Anki version *[ex: 2.1.23]*

## Additional context

Add any other context about the problem here.
```

2. set addon config to `debug`, do your reviews, and post the logs

![image](https://user-images.githubusercontent.com/775265/97776935-bbdd4780-1baf-11eb-9fda-afbb4f8d6a16.png)

![image](https://user-images.githubusercontent.com/775265/97776976-02cb3d00-1bb0-11eb-8069-917830914f4b.png)

**Comment by spectre008** [comment]
I see. Could you tell where I can change the colors?

**Comment by TheDemystifier** [comment]
> I see. Could you tell me where I can change the colors?

You need to post your debug!

**Comment by phu54321** [comment]
Closing due to insufficient information
