### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by lgddm** [trgkanki/remaining_time#28]
# Bug report

## Describe the bug

> dark mode is not working, so it is currently in light mode

## Reproduction step

> Steps to reproduce the behavior:

1. dark mode was set as true before last update
2. now it is currently in light mode regardless of whether dark mode is set to true or false

## Expected behavior

> dark mode "effect" would stay on even after update.

## Actual behavior

> dark mode "effect" is off.

## Anki/OS versions

- OS: macOS Catalina 10.15.6
- Anki version 2.1.35

## Additional context

> Add any other context about the problem here.

**Comment by legokeynes77** [comment]
Me too, the dark mode doesn’t work, it’s dazzling and causes me trouble

**Comment by phu54321** [comment]
Fixed. Check out the latest release
