### ISSUE TITLE
Can't find the progress bar

### ISSUE THREAD

**Issue by Miggy23** [trgkanki/remaining_time#29]
Since the add-on was update, the progress bar suddenly disappeared. I tried deleting and installing the add-on multiple times  but the progress bar is still nowhere to be found. I really tried looking for the problem myself but can't seem to

**Comment by phu54321** [comment]
OMG I uploaded [the wrong addon](https://ankiweb.net/shared/info/131336778) instead. Really sorry for the inconvenience.

Could you try updating again?

**Comment by Miggy23** [comment]
It's back to normal! Thank you so much! Really appreciate this add-on and was worried I messed it up
