### ISSUE TITLE
ETA showing time one hour later.

### ISSUE THREAD

**Issue by DyeffersonAz** [trgkanki/remaining_time#31]
# Bug report

## Description

> ETA is showing one hour after the actual time related to remaining time. i.e. 2 minutes remaining and ETA is 1h2m from now.

## Anki/OS versions

- OS: Windows 10
- Anki version 2.1

In any way I could clarify this issue, just say.
Thank you in advance.

**Comment by phu54321** [comment]
I have a big test 1 month later so sorry for late reply :( Definitely needs more clarification.

- How do you know that your eta is 2min?
- could you post your debug log? Set `debugLog` addon option to `true`, do some reviews until the bug is reproduced, and check out the log on help menu.
