### ISSUE TITLE
Add-on does not load. Edit: Read a solved issue which said version above 2.1.26 required. Will it not work on anki 2.1.15? 

### ISSUE THREAD

**Issue by Playandstudy** [trgkanki/remaining_time#37]
# Bug report

## Describe the bug
The add-on fails to load on Anki 2.1.15 using Windows 7 on my laptop

> A clear and concise description of what the bug is.

## Reproduction step

> Steps to reproduce the behavior:

1. Go to 'Anki'
2. See error: Error appears as soon as Anki opens

## Expected behavior

> A clear and concise description of what you expected to happen.
The add-on to work

## Actual behavior
Add-on did not  load
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/77135802/104279539-7c48ab00-54d0-11eb-8090-741214cc55fb.png)

## Anki/OS versions

- OS: *[ex: Windows 7]*
- Anki version *[ex: 2.1.15]*

## Additional context

> Add any other context about the problem here.

**Comment by mac-s-g** [comment]
I'm running into the same version running 2.1.15 on ubuntu.

**Comment by mac-s-g** [comment]
fwiw, the issue was resolved by upgrading anki to 2.1.38 (as expected).  thanks to @trgkanki for an awesome add-on!

**Comment by Playandstudy** [comment]
Thank you for the update, but I can't upgrade my anki version. (Using Windows 7, and a fatal error appears on upgrading)
Is there any other solution?

**Comment by phu54321** [comment]
You're using Anki 2.1.15, right?

It's quite hard for me to test lower anki versions, really.

**Comment by phu54321** [comment]
Anki 2.1.15 doesn't support hooking `webview_did_receive_js_message`, which is necessary for this addon to function.

https://github.com/ankitects/anki/commit/d54f719558bd2f04962d83ddf96830cec019a07f

This function has been added since 2.1.20, so you should upgrade at least to 2.1.20.
