### ISSUE TITLE
Remaining time greater than 1 day

### ISSUE THREAD

**Issue by anon135** [trgkanki/remaining_time#38]
# Feature request

## At the moment, remaining times greater than 1 day aren't shown by this add-on

As a university student who has large decks (some of which take several days, if not weeks to finish), it's always a bit frustrating that this otherwise excellent add-on doesn't show remaining times greater than 1 day.

## Making this an option (as opposed to the current "> day") would be very helpful to track multi-day progress.

Any help in this matter would be enormously appreciated.

**Comment by phu54321** [comment]
Uh do you run reviews 24hrs a day? Aren't you limiting # of new cards / review cards per day?

**Comment by thiswillbeyourgithub** [comment]
I think you should rather set daily limits and use this addon https://ankiweb.net/shared/info/738807903
