### ISSUE TITLE
[UI customization] Request to hide/customize time in Remaining Time

### ISSUE THREAD

**Issue by bradydjohnson** [trgkanki/remaining_time#4]
Love the progress bar with different colors based on button selected. I find the text displaying the remaining time distracting, though. Would it be possible to make the appearance of the text customized? Or perhaps hide the text?

**Comment by thiswillbeyourgithub** [comment]
Hi,
* It might be a step forward to remove the black line seperating the progress bar of the card.
* Instead of a coloured reset icon I think it would be easier to ignore a reset text button `[RESET]` 
* Maybe move the text alltogether to the bottom between "Show Answer" and "More" ? It might cause troubles with other addons tho

Hope that helped a bit :)

**Comment by phu54321** [comment]
Maybe I could add an option to display current retention rate at the bar.

![image](https://user-images.githubusercontent.com/775265/81043877-21e15e80-8eee-11ea-995e-15f370e70d14.png)

**Comment by phu54321** [comment]
Bump

**Comment by phu54321** [comment]
Since https://github.com/trgkanki/addon_template/commit/4863070e373dcc0fb7fec2928d6d52d52d04fd8f, this is now feasible.

ETA this sunday

**Comment by Helicle** [comment]
I'm commenting under this issue because I feel like it falls under the category of "customizing" time - it would be nice to have a config toggle to switch from a 24 hour ETA time (00:00-24:00) to a 12 hour one (12AM/12PM). Thank you for your addons, they make anki a lot better.

**Comment by phu54321** [comment]
You can hide time by setting `messageFormat` to blank on addon config. Appearance/styling of texts are yet to be stylized, however.

@Helicle Check out the addon config. There's a new option called `ETA12`.

**Comment by TheDemystifier** [comment]
Could you add a variable that shows remaining time in Hours and Minutes instead of just minutes?

**Comment by phu54321** [comment]
@TheDemystifier Sorry for late reply. Please open a new issue.

This issue has been solved at https://github.com/trgkanki/remaining_time/commit/c775f8ac9f8e742c318da8b99d30ad549ab0ec49. You can use custom CSS to hide the text.
