### ISSUE TITLE
Color meaning

### ISSUE THREAD

**Issue by masonc15** [trgkanki/remaining_time#40]
Hello,

I am enjoying the addon so far.  I have a question about the colors displayed on the timeline.  From the add-on page (https://ankiweb.net/shared/info/1508357010), I know that blue is correct and red is again.  But my timeline has a lot of green.  I'm wondering what that color means.  Here is a screenshot for reference:
![image](https://user-images.githubusercontent.com/7069521/107158819-8c7e6980-695a-11eb-9c82-1838f94363eb.png)

I am using the Auto Ease Factor addon as well which makes each card only have "Pass" or "Fail" as an option.  Not sure if this addon might be affecting the timeline.
Any information would be appreciated.  Thanks!

**Comment by felipemldias** [comment]
It means those are new cards

**Comment by masonc15** [comment]
That makes sense, it's just a little confusing.  It would make more sense if blue was new card and green was correct.  Is there a way to change these colors?  Thanks.

**Comment by phu54321** [comment]
Hmm. Yeah that color scheme would make sense. Maybe I could add an option for it.

**Comment by felipemldias** [comment]
I for one would love to be able to label a different color for each option (again, hard, good, easy). I actually looked a little trough the code and realized that's not currently feasible, but it would be really cool to have it match the button colors 

![image](https://user-images.githubusercontent.com/63819261/114308130-211b5a00-9ab9-11eb-8d5f-6311d1b5c83b.png)
