### ISSUE TITLE
i am really just trying to replace anki progress bar by glutanimate

### ISSUE THREAD

**Issue by entropicdays** [trgkanki/remaining_time#41]
# progress bar that simply shows how many cards have been completed as a percentage of total

## bar is too complicated and is visually distracting

i don't find it's estimation of remaining time accurate or useful and want a simple progress bar showing how many cards i have done as a proportion of due cards

## Suggested solution

add an option to disable the "estimated time remaining" functions and just show a straight progress bar

**Comment by thiswillbeyourgithub** [comment]
You can already do this in the addon settings
