### ISSUE TITLE
Quick Question: change the font size of the text

### ISSUE THREAD

**Issue by Cashburner** [trgkanki/remaining_time#44]
Nice addon, how can I change the font size of the text on the taskbar? I tried "font-size: 17px" in the css field you have in config but nothing happens. Sorry if what I said is stupid, I have very little programming experience. thanks a lot!

**Comment by felipemldias** [comment]
I don't know if this helps, but you could try the ankizoom (https://ankiweb.net/shared/info/538879081). It also increases the size of the content of cards, but it works for me.

**Comment by Cashburner** [comment]
> I don't know if this helps, but you could try the ankizoom (https://ankiweb.net/shared/info/538879081). It also increases the size of the content of cards, but it works for me.

already got this, but it seems to increase not only the card font size but also the addon's. I would love to find a way to decrease only the addon's font size.
