### ISSUE TITLE
When I press 'again', the progress bar treats it as though I pressed 'good'

### ISSUE THREAD

**Issue by anonymous8675** [trgkanki/remaining_time#47]
# Bug report

## Describe the bug

>When I am reviewing and I press the space bar for 'good', the progress bar advances as normal. However, when I press '1' on my keyboard for 'again', the progress bar advances the same as when I press good. It doesn't make a red section like it should, it just advances another blue section. 

> Also, when I press sync while reviewing cards it treats it as though I pressed 'again' and advances a red partition on the bar.

> Also, when I first open the deck, if I answer 'good' on the first card, nothing happens at all. However, every card I answer 'good' on after the first card works as expected.

## Reproduction step

> Steps to reproduce the behavior:

1. Click on the deck you wish to study
2. Click 'Study Now'
3. Press 'space bar' or '1' on the keyboard to produce issues described above

## Expected behavior

> I expect the bar to advance with a red section when I press 'again', and nothing to happen when I press sync while in review.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

## Anki/OS versions

- OS: Windows 10
- Anki version: 2.1.42

## Additional context

> I was simply looking for a progress bar add on that replaced glutanimates since he hasn't been keeping up with fixing his add on. He opened up a Patreon and a lot of people donated to him and yet he let 'Progress bar' go to shit. I'm hoping someone can eventually take the torch and make a reliable progress bar add on that works as expected.

**Comment by felipemldias** [comment]
I'm also facing this issue, it actually seems like the feedback is a little delayed, wrong answers will randomly appear later in the review bar. 

Perhaps you'd consider supporting TRGK on Patreon instead 😄 (https://www.patreon.com/trgk/posts). He has made several addons (including revamping Cloze hide all), but receives practically no support. 

I also feel we must recognize that addon authors are very frequently med students, such as glutanimate and trgk, who work on these on their free time. Anki is an open source project which is constantly changing its code, so maybe it's not a reasonable expectation to have their addons be always updated. 

Anki redesign (https://ankiweb.net/shared/info/1914733489) is a great example of a wonderful addon with a progress bar included but which the author has already announced he wont be supporting any further.
