### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rseisinger** [trgkanki/remaining_time#49]
# Bug report

## Describe the bug

> A clear and concise description of what the bug is.

Error when first restarting Anki after installing this add-on

## Reproduction step

> Steps to reproduce the behavior:

Install, restart Anki

## Expected behavior

No bugs

## Actual behavior

![image](https://user-images.githubusercontent.com/38671395/112721307-8f68f580-8ed9-11eb-97a4-e1b1785bc5a1.png)

## Anki/OS versions

- OS: 11.2
- Anki version Version 2.1.15 (442df9d6)
Qt 5.12.1 PyQt 5.11.3

## Additional context

> Add any other context about the problem here.

**Comment by kuba58426** [comment]
I had the same problem on Ubuntu 20.04. It turned out that I have an outdated version of Anki as I had installed it from the default repo. I see that you have Anki 2.1.15 (as did I) but the latest one is 2.1.42. Try installing Anki from [the ankiweb website](https://apps.ankiweb.net/).
