### ISSUE TITLE
Flags are hidden

### ISSUE THREAD

**Issue by Medicine1** [trgkanki/remaining_time#5]
When a card is flagged, we currently cannot see whether the card is flagged during review because the remaining_time bar (when at the top) blocks the flag. Previous versions of remaining_time did not hide the flag (this was around Jan. or Feb. 2020 and in Anki 2.1.20).

Please allow card flags to be visible again and compatible with remaining_time. Thank you for a useful addon.

**Comment by phu54321** [comment]
Need to get things done. ETA today (KST)

**Comment by phu54321** [comment]
Fixed on afee175c2e80bf714e35d82e7ddd4b301269f362
