### ISSUE TITLE
Add-on fails to load 

### ISSUE THREAD

**Issue by dylanlucia** [trgkanki/remaining_time#71]
I tried installing the add-on and upon opening Anki I got the add-on changelog splash screen, then this error about 'gui_hooks' seen in the screenshot.
![Screenshot](https://i.imgur.com/U7qw1d9.png)
Enabling debug mode in the config does not change the error.
Anki Version 2.1.12 (eef86bf3)

**Comment by schroederjulius** [comment]
This issue seems to have been fixed by Anki Version ⁨2.1.56 (07fd88dd)⁩.

**Comment by schroederjulius** [comment]
Maybe there is a conflict with another add on. To check that, you can can hold the shift key down while starting Anki to temporarily disable all add-ons.

**Comment by phu54321** [comment]
Use newer version of Anki. 2.1.12 is too outdated
