### ISSUE TITLE
[Request] Pause Button

### ISSUE THREAD

**Issue by distract6541** [trgkanki/remaining_time#76]
Can a pause button be added?

Currently if I go to the bathroom or go eat, when I come back the addon assumes I've been stuck on a card for 20 minutes and dramatically changes my ETA and remaining time. To resolve this, I usually restart the timer.

But I was wondering if implementing a pause button that can also hook into when a card is flipped or answered (for automatic resuming) would be possible.

If it seems like it's gonna be a lot of work, I wouldn't worry about it. Just first-world pains.

**Comment by distract6541** [comment]
I'm closing this because it turns out I'm dumb. I wasn't reading the numbers correctly.

**Comment by phu54321** [comment]
Yeah addon works well even with pauses.
