### ISSUE TITLE
css styling. 

### ISSUE THREAD

**Issue by TowelSniffer** [trgkanki/remaining_time#8]
when styling a link in css it will effect this addon. It's not a major concern of mine as its easy to work around but I figured might as well report it. 

example css:
a{   background-color: #EEEEEE;
    padding: 8px 20px;
    text-decoration:none;
    font-weight:bold;
    border-radius:5px;
    cursor:pointer;
color: black!important; }

![image](https://user-images.githubusercontent.com/52064198/91088599-35096d00-e64a-11ea-8e0d-ebd618b9daaf.png)

**Comment by phu54321** [comment]
Not really fixable. Please use <div> or <span> for custom styling.
